Add missing cache keys for test job.
cisagov/skeleton-docker pull request #35
Opened 2020-10-08 18:34 UTC by felddy

Fixes #30

# 

## 🗣 Description

Add missing cache keys for test job.

## 💭 Motivation and Context

## 🧪 Testing

## 📷 Screenshots (if appropriate)

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-10-08 18:44 UTC, dav3r approved these changes
💯

2020-10-08 19:35 UTC, jsf9k approved these changes
:zap:

2020-10-09 15:01 UTC, felddy commented
@mcdonnnj does this look good to you?

2020-10-09 16:33 UTC, mcdonnnj requested changes
Thanks for getting this done. :godmode: Please see my one change.

2020-10-09 16:33 UTC, mcdonnnj commented on .github/workflows/build.yml
> +            ${{ hashFiles('**/.pre-commit-config.yaml') }}"
```suggestion
            ${{ hashFiles('**/requirements-test.txt') }}-\
            ${{ hashFiles('**/requirements.txt') }}"
```
`.pre-commit-config.yaml` is only used by the `lint` workflow.

2020-10-09 19:27 UTC, mcdonnnj approved these changes
💪💪💪

2020-10-09 19:50 UTC, merged